name: React Native iOS CI

on:
  push:
    branches: [ staging ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      - name: Install JS dependencies
        run: yarn install --frozen-lockfile

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          bundle install
          bundle exec pod install

      - name: Build iOS app
        run: |
          cd ios
          xcodebuild -workspace cicd_reactnative.xcworkspace -scheme cicd_reactnative -sdk iphonesimulator -configuration Debug build

      # Optional: Run Jest tests
      - name: Run tests
        run: yarn test